{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modelsummary
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modelsummary_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modelsummary/modelsummary_{{ version }}.tar.gz
  sha256: b0e784edfafe6c70fcd79c2437a47865a07dfb3f7292a38d76c2c819a69a2df6

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-broom
    - r-checkmate
    - r-data.table
    - r-generics
    - r-glue
    - r-insight >=0.16.1
    - r-kableextra >=1.2.1
    - r-parameters >=0.17.0
    - r-performance
    - r-tables
  run:
    - r-base
    - r-broom
    - r-checkmate
    - r-data.table
    - r-generics
    - r-glue
    - r-insight >=0.16.1
    - r-kableextra >=1.2.1
    - r-parameters >=0.17.0
    - r-performance
    - r-tables

test:
  commands:
    - $R -e "library('modelsummary')"           # [not win]
    - "\"%R%\" -e \"library('modelsummary')\""  # [win]

about:
  home: https://vincentarelbundock.github.io/modelsummary/
  license: GPL-3.0-only
  summary: Create beautiful and customizable tables to summarize several statistical models side-by-side. Draw coefficient plots, multi-level cross-tabs, dataset summaries, balance tables (a.k.a. "Table 1s"), and correlation matrices. This package supports dozens of statistical models, and it can produce tables in HTML,
    LaTeX, Word, Markdown, PDF, PowerPoint, Excel, RTF, JPG, or PNG. Tables can easily be embedded in 'Rmarkdown' or 'knitr' dynamic documents.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - izahn
    - conda-forge/r
