{% set version = "2.5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-modelsummary
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modelsummary_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modelsummary/modelsummary_{{ version }}.tar.gz
  sha256: 9629b42e407d08623cd89655034ff31c5cb05bacd292cf88871258dbdecef790

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.3.1
    - r-data.table >=1.15.2
    - r-generics
    - r-glue
    - r-insight >=0.19.11
    - r-parameters >=0.21.7
    - r-performance >=0.11.0
    - r-tables >=0.9.17
    - r-tinytable >=0.3.0
  run:
    - r-base
    - r-checkmate >=2.3.1
    - r-data.table >=1.15.2
    - r-generics
    - r-glue
    - r-insight >=0.19.11
    - r-parameters >=0.21.7
    - r-performance >=0.11.0
    - r-tables >=0.9.17
    - r-tinytable >=0.3.0

test:
  commands:
    - $R -e "library('modelsummary')"           # [not win]
    - "\"%R%\" -e \"library('modelsummary')\""  # [win]

about:
  home: https://vincentarelbundock.github.io/modelsummary/
  license: GPL-3.0-only
  summary: Create beautiful and customizable tables to summarize several statistical models side-by-side. Draw coefficient plots, multi-level cross-tabs, dataset summaries, balance tables (a.k.a. "Table 1s"), and correlation matrices. This package supports dozens of statistical models, and it can produce tables in HTML,
    LaTeX, Word, Markdown, PDF, PowerPoint, Excel, RTF, JPG, or PNG. Tables can easily be embedded in 'Rmarkdown' or 'knitr' dynamic documents.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
